# Configuration pour le secret scanning de GitHub
# Exclut les fichiers de test contenant des données factices

paths-ignore:
  # Fichiers de test avec données sensibles factices
  - '**/test_*.txt'
  - '**/test_security_data.txt'
  - '**/sample_data.txt'
  - '**/*test_data*'
  - '**/mock_*.txt'

  # Dossiers de test
  - '**/test/**'
  - '**/tests/**'
  - '**/TestData/**'
